# This is a basic workflow to help you get started with Actions

name: Dogfood

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: aareet/move-labeled-or-milestoned-issue@v2.1
      with:
        action-token: "${{ secrets.MY_TOKEN }}"
        project-url: "https://github.com/aareet/move-labeled-or-milestoned-issue/projects/1"
        column-name: "Needs triage"
        label-name: "test"
        add-as-note: true 